
trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@2
    displayName: 'Install Power Platform Tools'

  - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@2
    displayName: 'Export solution from Dev'
    inputs:
      Environment: '$(ENVIRONMENT_URL_DEV)'
      ApplicationId: '$(CLIENT_ID)'
      TenantId: '$(TENANT_ID)'
      ClientSecret: '$(CLIENT_SECRET)'
      SolutionName: 'Test'
      OutputFile: 'managed-solution.zip'
      Managed: true

  - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.import-solution.PowerPlatformImportSolution@2
    displayName: 'Import solution to Prod'
    inputs:
      Environment: '$(ENVIRONMENT_URL_PROD)'
      ApplicationId: '$(CLIENT_ID)'
      TenantId: '$(TENANT_ID)'
      ClientSecret: '$(CLIENT_SECRET)'
      SolutionInputFile: 'managed-solution.zip'
